image: node:12.15.0-alpine3.11

before_script:
  - npm install

cache:
  policy: pull-push
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm run lint
    - npm run test

deploy:
  stage: deploy
  only:
    - tags
  script:
    - npm run publish

pages:
  stage: deploy
  only:
    - tags
  script:
    - mv dist/index.js public/index.js
  artifacts:
    paths:
      - public/
